# Site settings
title: Suman Kisku
header-img: img/home-bg.jpg
email: sumankisku@outlook.com
copyright_name: Suman Kisku
description: "Suman Kisku. What I have done all the day? Web Design Inspirations and Tips. Keep my memories on blog."
baseurl: "http://sumankisku.github.io"
url: "http://sumankisku.github.io"
twitter_username: suman_kisku
github_username:  SumanKisku
facebook_username:  suman.kisku2
email_username:  sumankisku1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
