# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Suman Kisku
email: sumankisku1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I am Suman Kisku a student. I like to play with HTML, CSS & JavaScript. Intrested in front-end development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sumankisku.github.io" # the base hostname & protocol for your site
twitter_username: suman_kisku
github_username:  SumanKisku

# Build settings
markdown: kramdown
